### ISSUE TITLE
发现问题，若json配置文件中的"console"的enable设置为flase,则运行直接崩溃

### ISSUE THREAD

**Issue by yangyongzhen** [jeanphorn/log4go#15]
"console": {
        "enable": true,
        "level": "FINE"
    },这个配置，若配置为enable:false,则直接崩溃。发现原因是category.go的第65行，
default_filter := Global["stdout"]
if lvl > default_filter.Level {}
这里的default_filter 为nil 。
解决办法是这里需要加个判断吧。
今天突然想关掉命令行日志，只保留文件日志发现的这个问题。

**Comment by jeanphorn** [comment]
fixed

**Comment by jeanphorn** [comment]
fixed
