### ISSUE TITLE
go get failed

### ISSUE THREAD

**Issue by jdevsean** [jeanphorn/log4go#8]
why i run "got get github.com/jeanphorn/log4go ",the console print this message:
 github.com/jeanphorn/log4go
go/src/github.com/jeanphorn/log4go/jsonconfig.go:68:22: undefined: dst
go/src/github.com/jeanphorn/log4go/jsonconfig.go:71:18: undefined: file.ReadFile
go/src/github.com/jeanphorn/log4go/jsonconfig.go:77:20: undefined: dst

**Comment by Avik1993** [comment]
Facing same issue.

**Comment by jeanphorn** [comment]
@yourbest @Avik1993 @jdevsean  sorry， I forgot test before.   I've fixed.
